services:
  kos-v7:
    build: .
    container_name: kos-v7
    ports:
      - "3000:3000"
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
      - ./public/uploads:/app/public/uploads
    environment:
      - DATABASE_URL=file:./dev.db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: always
