services:
  kos-v7:
    build: .
    container_name: kos-v7
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma
      - ./public/uploads:/app/public/uploads
      - ./public/shinsung/uploads:/app/public/shinsung/uploads
      - ./public/coating/uploads:/app/public/coating/uploads
      - ./public/notepad/uploads:/app/public/notepad/uploads
    environment:
      - DATABASE_URL=file:./prisma/dev.db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: always
